# RAG System Prototype for Course Material Question Answering

This notebook demonstrates a small scale implementation of a Retrieval-Augmented Generation (RAG) system. The system processes and indexes sample course material, retrieves relevant chunks based on a user query, builds a prompt, and finally generating an answer using a language model (LLM).

In [1]:
# Uncomment and run the following cell to install required packages if needed
# !pip install sentence-transformers faiss-cpu openai
# !pip install transformers accelerate torch
# !pip install sacrebleu rouge-score bert-score
# !pip install nltk

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from sacrebleu import corpus_bleu
from rouge_score import rouge_scorer
from bert_score import score as bert_score

# LLM Agent Class

In [3]:
from openai import OpenAI

openAiKeyFile = open('openaikey.txt', 'r', encoding='utf-8')
OpenAI_API_KEY = openAiKeyFile.readline().strip()
openAiKeyFile.close()
openai_models = [
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-16k",
    "gpt-4-turbo",
    "gpt-4",
    "gpt-4o-mini",
    "gpt-4o"
]
LLM_Model = openai_models[0]

# Define the LlmAgent class
class LlmAgent:
    def __init__(self, name, key, model, temperature):
        self.name = name
        self.temperature = temperature
        self.model = model
        self.client = OpenAI(api_key=key)
        self.messages = []

    def initializeAgent(self, system_prompt):
        self.messages.append({"role": "system", "content": system_prompt})

    def sendMessage(self, userinput):
        self.messages.append({"role": "user", "content": userinput})

    def getResponse(self):
        response = self.client.chat.completions.create(model=self.model, messages=self.messages)
        response_message = response.choices[0].message.content
        self.messages.append({"role": "assistant", "content": response_message})
        return response_message

# Define a function to create an agent
def create_agent(role_name, description, key, model=LLM_Model, temperature=1.0):
    agent = LlmAgent(name=role_name, key=key, model=model, temperature=temperature)
    system_prompt = f"""
    You are the {role_name}. {description}
    """
    agent.initializeAgent(system_prompt)
    return agent

# RAG Functions

In [4]:
import numpy as np
import nltk
from sentence_transformers import SentenceTransformer
import faiss

# download nltk data
nltk.download('all')

# take in text with punctuation and split into chunks
def chunk_text(text, chunk_size, overlap):
    sentences = nltk.sent_tokenize(text)
    chunks = []
    start = 0
    while start < len(sentences):
        chunk = sentences[start: start + chunk_size]
        chunks.append(' '.join(chunk))
        start += (chunk_size - overlap)
    return chunks

# def chunk_text(text, chunk_size, overlap):
#     """
#     Splits the text into chunks of a given size with an overlap to maintain context.
#     """
#     words = text.split()
#     chunks = []
#     start = 0
#     while start < len(words):
#         chunk = words[start: start + chunk_size]
#         chunks.append(' '.join(chunk))
#         start += (chunk_size - overlap)
#     return chunks

# Load a pre-trained Sentence Transformer model for embedding
model = SentenceTransformer('all-MiniLM-L6-v2')

def embed_texts(texts):
    """
    Computes vector embeddings for a list of texts using the pre-trained model.
    """
    embeddings = model.encode(texts)
    return embeddings

def build_faiss_index(embeddings):
    """
    Builds a FAISS index from the given embeddings for efficient similarity search.
    """
    dim = embeddings.shape[1]
    #index = faiss.IndexFlatL2(dim)
    index = faiss.IndexFlatIP(dim) # inner product
    faiss.normalize_L2(embeddings) # new =)
    index.add(embeddings.astype('float32'))
    #index.add(embeddings)
    return index

def keyword_score(query, chunk):
    query = query.split() # ["What", "is", "y"]
    chunk = chunk.split() # ["What", "is", "y"]

    query_words = {word.strip('.,!?').lower() for word in query}
    chunk_words = {word.strip('.,!?').lower() for word in chunk}
    return len(query_words.intersection(chunk_words))

def retrieve(query, chunks, index, k):
    """
    Retrieves the top-k most relevant text chunks for a given query.
    First, retieve 2*k chunks based on the embeddings.
    Second, sort them based on the actual keywords relevance.
    Third, picks the top-k chunks.
    """
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding) # new =)
    D, I = index.search(np.array(query_embedding).astype('float32'), 2 * k)
    retrieved_chunks = [chunks[i] for i in I[0]]

    retrieved_chunks.sort(key = lambda chunk: keyword_score(query, chunk), reverse = True)

    return retrieved_chunks[:k]
    

    #return retrieved_chunks
def build_prompt(query, retrieved_chunks):
    """
    Combines the user query with retrieved context chunks to build a prompt for the LLM.
    """
    context_chunks = "".join(retrieved_chunks)

    prompt = f"""You are a helpful teaching assistant answering questions. 
                Please read the **Context** and **nQuestion** below and try to extract a cohesive answer from the context.
                Do not use your own knowledge and stick to the context being given to you.
                Please give a brief answer that matches the context wording as much as possible.\n
                **Context**: {context_chunks}\n
                **Question**: {query}"""
    return prompt

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /Users/754346/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /Users/754346/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /Users/754346/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to /Users/754346/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to /Users/754346/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to /Users/754346/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet2022 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package wordnet2022 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to
[nltk_data]    |     /Users/754346/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection all

# Processing and Indexing Course Material

In [5]:
import os
import numpy as np
from tqdm import tqdm

# 2.0: Helper to load all .txt files from given folders
def load_all_texts(dirs, extensions=(".txt",)):
    docs = {}
    for d in dirs:
        for fname in os.listdir(d):
            if fname.lower().endswith(extensions):
                path = os.path.join(d, fname)
                with open(path, "r", encoding="utf-8") as f:
                    docs[fname] = f.read()
    return docs

# 2.1: Load documents
directories = ["processed_transcripts", "lecture_notes"]
documents = load_all_texts(directories)

# 2.2: Chunk each document and collect all chunks

all_chunks = []
for fname, text in documents.items():
    print(f"\n--- Processing '{fname}' ---")
    
    # Chunk it
    chunks = chunk_text(text, chunk_size=10, overlap=3)
    
    # show a progress bar instead of printing "-" lines
    for _ in tqdm(chunks, desc=f"Chunking {fname}", unit="chunk"):
        pass
    
    all_chunks.extend(chunks)

print(f"\nTotal chunks created: {len(all_chunks)}")

# 2.3: Embed all chunks
embeddings = embed_texts(all_chunks)
embeddings_np = np.array(embeddings).astype("float32")

# 2.4: Build the FAISS index
index = build_faiss_index(embeddings_np)

print("✅ All documents processed, embedded, and indexed.")

--- Processing 'lecture-7.txt' ---

Chunking lecture-7.txt: 100%|██████████████████████████| 54/54 [00:00<00:00, 770382.37chunk/s]

--- Processing 'lecture-6.txt' ---

Chunking lecture-6.txt: 100%|█████████████████████████| 63/63 [00:00<00:00, 1164057.94chunk/s]

--- Processing 'lecture-4.txt' ---

Chunking lecture-4.txt: 100%|█████████████████████████| 61/61 [00:00<00:00, 1382986.72chunk/s]

--- Processing 'lecture-5.txt' ---

Chunking lecture-5.txt: 100%|█████████████████████████| 45/45 [00:00<00:00, 1091003.93chunk/s]

--- Processing 'lecture-1.txt' ---

Chunking lecture-1.txt: 100%|█████████████████████████| 67/67 [00:00<00:00, 1813021.73chunk/s]

--- Processing 'lecture-2.txt' ---

Chunking lecture-2.txt: 100%|█████████████████████████| 53/53 [00:00<00:00, 2058315.85chunk/s]

--- Processing 'lecture-3.txt' ---

Chunking lecture-3.txt: 100%|█████████████████████████| 56/56 [00:00<00:00, 2078593.13chunk/s]

--- Processing 'lecture-18.txt' ---

Chunking lecture-18.txt: 100%|████████████████████████| 65/65 [00:00<00:00, 2291006.39chunk/s]

--- Processing 'lecture-19.txt' ---

Chunking lecture-19.txt: 100%|████████████████████████| 46/46 [00:00<00:00, 1910277.07chunk/s]

--- Processing 'lecture-21.txt' ---

Chunking lecture-21.txt: 100%|████████████████████████| 82/82 [00:00<00:00, 1297860.11chunk/s]

--- Processing 'lecture-20.txt' ---

Chunking lecture-20.txt: 100%|████████████████████████| 64/64 [00:00<00:00, 2556528.15chunk/s]

--- Processing 'lecture-12.txt' ---

Chunking lecture-12.txt: 100%|████████████████████████| 77/77 [00:00<00:00, 3329499.05chunk/s]

--- Processing 'lecture-13.txt' ---

Chunking lecture-13.txt: 100%|████████████████████████| 68/68 [00:00<00:00, 2716311.16chunk/s]

--- Processing 'lecture-11.txt' ---

Chunking lecture-11.txt: 100%|████████████████████████| 57/57 [00:00<00:00, 2043378.87chunk/s]

--- Processing 'lecture-10.txt' ---

Chunking lecture-10.txt: 100%|████████████████████████| 46/46 [00:00<00:00, 1277734.99chunk/s]

--- Processing 'lecture-14.txt' ---

Chunking lecture-14.txt: 100%|████████████████████████| 68/68 [00:00<00:00, 2616630.02chunk/s]

--- Processing 'lecture-15.txt' ---

Chunking lecture-15.txt: 100%|████████████████████████| 80/80 [00:00<00:00, 2995931.43chunk/s]

--- Processing 'lecture-17.txt' ---

Chunking lecture-17.txt: 100%|████████████████████████| 67/67 [00:00<00:00, 2036364.99chunk/s]

--- Processing 'lecture-16.txt' ---

Chunking lecture-16.txt: 100%|████████████████████████| 63/63 [00:00<00:00, 2516582.40chunk/s]

--- Processing 'lecture-8.txt' ---

Chunking lecture-8.txt: 100%|█████████████████████████| 58/58 [00:00<00:00, 2133944.14chunk/s]

--- Processing 'lecture-9.txt' ---

Chunking lecture-9.txt: 100%|█████████████████████████| 66/66 [00:00<00:00, 2539670.31chunk/s]

--- Processing 'Hands_On_ML_Rewritten.txt' ---

Chunking Hands_On_ML_Rewritten.txt: 100%|█████████████████| 2/2 [00:00<00:00, 99864.38chunk/s]

--- Processing 'Kernel_SVMs_Rewritten.txt' ---

Chunking Kernel_SVMs_Rewritten.txt: 100%|█████████████████| 2/2 [00:00<00:00, 94254.02chunk/s]

--- Processing 'PRML_Slides_1_Rewritten.txt' ---

Chunking PRML_Slides_1_Rewritten.txt: 100%|███████████████| 1/1 [00:00<00:00, 55924.05chunk/s]

--- Processing 'Matrix_Factorization_Rewritten.txt' ---

Chunking Matrix_Factorization_Rewritten.txt: 100%|████████| 1/1 [00:00<00:00, 55924.05chunk/s]

--- Processing 'SGD_Lecture_Rewritten.txt' ---

Chunking SGD_Lecture_Rewritten.txt: 100%|█████████████████| 1/1 [00:00<00:00, 22192.08chunk/s]

--- Processing 'Transformers_Lecture_Rewritten.txt' ---

Chunking Transformers_Lecture_Rewritten.txt: 100%|████████| 2/2 [00:00<00:00, 91180.52chunk/s]

--- Processing 'Linear_Algebra_ReviewNotes_Rewritten.txt' ---

Chunking Linear_Algebra_ReviewNotes_Rewritten.txt: 100%|██| 2/2 [00:00<00:00, 64527.75chunk/s]

--- Processing 'Linear_Algebra_Review_Rewritten.txt' ---

Chunking Linear_Algebra_Review_Rewritten.txt: 100%|███████| 2/2 [00:00<00:00, 57456.22chunk/s]

--- Processing 'Logistic_Regression_Rewritten.txt' ---

Chunking Logistic_Regression_Rewritten.txt: 100%|████████| 2/2 [00:00<00:00, 118149.41chunk/s]

--- Processing 'Transformers_Lecture_Part2_Rewritten.txt' ---

Chunking Transformers_Lecture_Part2_Rewritten.txt: 100%|██| 2/2 [00:00<00:00, 99864.38chunk/s]

--- Processing 'Perceptron_SVM_Rewritten.txt' ---

Chunking Perceptron_SVM_Rewritten.txt: 100%|█████████████| 3/3 [00:00<00:00, 131072.00chunk/s]

--- Processing 'Probability_Theory_Rewritten.txt' ---

Chunking Probability_Theory_Rewritten.txt: 100%|██████████| 1/1 [00:00<00:00, 33554.43chunk/s]

--- Processing 'Regularization_Regression_Rewritten.txt' ---

Chunking Regularization_Regression_Rewritten.txt: 100%|███| 1/1 [00:00<00:00, 47662.55chunk/s]

--- Processing 'SVD_Regression_Rewritten.txt' ---

Chunking SVD_Regression_Rewritten.txt: 100%|██████████████| 1/1 [00:00<00:00, 49932.19chunk/s]

--- Processing 'Intro_to_DL_Rewritten.txt' ---

Chunking Intro_to_DL_Rewritten.txt: 100%|████████████████| 4/4 [00:00<00:00, 166111.05chunk/s]

--- Processing 'Clustering_Lecture_Notes_Rewritten.txt' ---

Chunking Clustering_Lecture_Notes_Rewritten.txt: 100%|███| 5/5 [00:00<00:00, 265462.28chunk/s]

--- Processing 'SVMs_Duality_Rewritten.txt' ---

Chunking SVMs_Duality_Rewritten.txt: 100%|███████████████| 2/2 [00:00<00:00, 104857.60chunk/s]

--- Processing 'Classification_Lecture_Rewritten.txt' ---

Chunking Classification_Lecture_Rewritten.txt: 100%|█████| 2/2 [00:00<00:00, 101067.57chunk/s]

--- Processing 'Linear_Regression_Rewritten.txt' ---

Chunking Linear_Regression_Rewritten.txt: 100%|███████████| 2/2 [00:00<00:00, 80659.69chunk/s]

Total chunks created: 1344

✅ All documents processed, embedded, and indexed.

# Retrival and Prompting

In [7]:
# Step 3.1: Define a sample query
#query = "What programming paradigms does Python support?"
query = "Why does the SVD of a matrix reveal its rank?"

# Step 3.2: Retrieve the top-k relevant chunks from the course material
retrieved_chunks = retrieve(query, all_chunks, index, k=5)
print("\nRetrieved Chunks:\n")
for chunk in retrieved_chunks:
    print(chunk)
    print("-"*50)

# Step 3.3: Build a prompt combining the query and retrieved context
prompt = build_prompt(query, retrieved_chunks)
print("\nPrompt for LLM:\n")
print(prompt)
# display(Latex(prompt))

Retrieved Chunks:

again, a very beautiful characterization of the singular value. decomposition is the following: right, if Matrix a? I haven't spoken about rank far, but if Matrix a has rank R, okay, and R has to be less than equal to minimum of MN, and if m is greater than equal to n, it means that R is less than equal to n. R is the rank of the Matrix and that's exactly equal to the number of nonzero singular values. that's really the almost numerically the best way to determine the rank of a matrix is to do an SVD. okay, let me write it out. this means that Sigma 1 is greater than equal to Sigma 2, is greater than equal to Sigma r, and this is greater than zero, and what that means is that Sigma r + 1 = Sigma r + 2 to Sigma n, equal Z. okay, and then if I think about a, my Matrix a, then I have: a is r, n to r m. this is its Ma V1, as we saw to U1, Sigma 1, V2 to U2, Sigma 2, VR to ur, Sigma r and v? r + 1. it maps to zero because the rank is r, and similarly, V? r+ r, v, n is mapped to zero. note that R may be equal to n, in which case there are- there is no Vector- VR + 1 through VN, okay, and then we have a transpose which Maps our M to or n. and I have that U1 is m mapped to V1, Sigma 1, U2 is mapped to vs2, Sigma 2. Ur is mapped to VR, Sigma R, and then Ur + 1 is mapped to zero and we are assuming that m is greater than equal to n, for now Ur r + 1 through u, m is mapped to zero.
--------------------------------------------------
r+ r, v, n is mapped to zero. note that R may be equal to n, in which case there are- there is no Vector- VR + 1 through VN, okay, and then we have a transpose which Maps our M to or n. and I have that U1 is m mapped to V1, Sigma 1, U2 is mapped to vs2, Sigma 2. Ur is mapped to VR, Sigma R, and then Ur + 1 is mapped to zero and we are assuming that m is greater than equal to n, for now Ur r + 1 through u, m is mapped to zero. the beautiful thing that the SVD does okay is it provides a very special provides- sorry, R is a little funky. it provides an orthogonal basis for the four fundamental subspaces of a. and what are the four fundamental subspaces? and some of you might have seen this in your, in your linear algebra class, it's the column space of the Matrix, a, which is often denoted as range space of a. the other is the row space of the Matrix and you probably saw right that the row rank in in your, in your undergraduate linear algebra course, that the row rank is the same as the column rank, right, and it just falls out of the SVD, right? it's the. I can write the range space of a transpose. then I have the null space, which is m space of a. I have n space of a of a transpose is equal to m space of aace. I don't need to get all fancy over here.
--------------------------------------------------
but also, you know, you can truncate the SVD at any K. you can, you know, if the full SVD is U, Sigma, V, transpose, as given over here, right, the thin, the. the thin SVD is sometimes called this U hat, which takes where m is greater than equal to n, and you take the first n singular vectors, U hat, Sigma hat, V, had, transpose. but you can truncate it at any K. you can just take U1, U2, for example, or U1, U2, u3, and then take the corresponding singular values- they are of course ordered in decreasing order- and then also the corresponding v's, and that is sometimes called the K truncated SVD. and one of the really nice properties of the SVD is that that gives the best rank K approximation to the given Matrix, right? for example, here you know, if you have a given Matrix a and you want to find out the best ranky approximation of this Matrix, then you can basically just take, you know, U, K, Sigma K, VK transpose. where UK is n by M by K, maybe I should write it over here: Sigma U, UK belongs to our M by K, Sigma K belongs to r, k by K and VK belongs to R NYK, okay, and that gives you the, the, the S, the best singular value, best truncated, best rank ranky approximation. okay, then we went back to Le squares regression and we saw that LE squares regression, if you analyze it using the SVD, it's just the orthogonal projector onto the rain space of the design Matrix, which is X transpose, right, which is made of the training samples. today we will kind of talk a little bit more about regression, some of the issues that there are with just doing regression as we've talked about it, for example e squares regression- and talk about something that is really needed to make the regression better, which is regularization in regression, and there we'll look at a particular way to regularize which makes the prediction better, and we will see that we can analyze this method, called Ridge regression, quite well by looking at the singular value, decomposition. okay, reminder that regression is, you know, I have training data and XI, Yi, XI is D dimensional D features the Y's. since we are talking about regression, these are real numbers and linear regression is basically taking a linear combination which is W + W1, X1 + W2, X2 plus WB, XD.
--------------------------------------------------
okay, and it is. it is true for all, okay, okay, which means that, and remember that AK is equal to UK K, Sigma K we okay with. with that I kind of conclude talking about the singular value de composition. but it's really a, an amazing decomposition among all Matrix decompositions that exist. any questions far? I'm now going to move on to regression and see how the SVD can be. you know how the SVD helps us over there. I have a question: if I made those Sigma values, the singular values, Sigma 1 to Sigma n, okay, when we do the, the K rank, you mentioned that these are kind of sorted: the sigma is, the is the greatest one and the biggest, and then all the way to Sigma n. when we the the K rank thing are the, let's say we do k equals 2, Sigma 1 and sigma 2 are the, the exact value of the, the full de composite, exactly they are exactly this Sigma one and this Sigma 2. basically it's saying that I can take this decomposition, which is the full SVD, and I can basically just take any K left singular vectors, any K, the top K singular values and the top K right singular vector. and If I multiply them out, UK Sigma K, VK transpose, then among all possible ranky approximations of a, this is the closest to a. that's pretty powerful. yes, it's.
--------------------------------------------------
I have a question: if I made those Sigma values, the singular values, Sigma 1 to Sigma n, okay, when we do the, the K rank, you mentioned that these are kind of sorted: the sigma is, the is the greatest one and the biggest, and then all the way to Sigma n. when we the the K rank thing are the, let's say we do k equals 2, Sigma 1 and sigma 2 are the, the exact value of the, the full de composite, exactly they are exactly this Sigma one and this Sigma 2. basically it's saying that I can take this decomposition, which is the full SVD, and I can basically just take any K left singular vectors, any K, the top K singular values and the top K right singular vector. and If I multiply them out, UK Sigma K, VK transpose, then among all possible ranky approximations of a, this is the closest to a. that's pretty powerful. yes, it's. it's a beautiful property and somewhat surprising, if you know, if you, if you think about it, really it's kind of a. if I just look at this particular particular problem over here and I think about trying to solve it, this particular problem, it's not clear that there is a closed rank solution. this problem is not really even convex, because rank is not a kind of convex function, but it's just kind of the wonders of single value decomposition, that have this nested property. it's basically a nested property. yeah, yeah, it's just, you can some sort of partition, The Matrix you want, and then that, yeah, that's yeah beautiful, yeah, yeah, yeah. I mean I can't stop gushing about the SVD, but it's really kind of a remarkable decomposition. it helps us in. I said, it helps us in interpretation of many things.
--------------------------------------------------

Prompt for LLM:

You are a helpful teaching assistant answering questions.
                Please read the **Context** and **nQuestion** below and try to extract a cohesive answer from the context.
                Do not use your own knowledge and stick to the context being given to you.
                Please give a brief answer that matches the context wording as much as possible.

                **Context**: again, a very beautiful characterization of the singular value. decomposition is the following: right, if Matrix a? I haven't spoken about rank far, but if Matrix a has rank R, okay, and R has to be less than equal to minimum of MN, and if m is greater than equal to n, it means that R is less than equal to n. R is the rank of the Matrix and that's exactly equal to the number of nonzero singular values. that's really the almost numerically the best way to determine the rank of a matrix is to do an SVD. okay, let me write it out. this means that Sigma 1 is greater than equal to Sigma 2, is greater than equal to Sigma r, and this is greater than zero, and what that means is that Sigma r + 1 = Sigma r + 2 to Sigma n, equal Z. okay, and then if I think about a, my Matrix a, then I have: a is r, n to r m. this is its Ma V1, as we saw to U1, Sigma 1, V2 to U2, Sigma 2, VR to ur, Sigma r and v? r + 1. it maps to zero because the rank is r, and similarly, V? r+ r, v, n is mapped to zero. note that R may be equal to n, in which case there are- there is no Vector- VR + 1 through VN, okay, and then we have a transpose which Maps our M to or n. and I have that U1 is m mapped to V1, Sigma 1, U2 is mapped to vs2, Sigma 2. Ur is mapped to VR, Sigma R, and then Ur + 1 is mapped to zero and we are assuming that m is greater than equal to n, for now Ur r + 1 through u, m is mapped to zero.r+ r, v, n is mapped to zero. note that R may be equal to n, in which case there are- there is no Vector- VR + 1 through VN, okay, and then we have a transpose which Maps our M to or n. and I have that U1 is m mapped to V1, Sigma 1, U2 is mapped to vs2, Sigma 2. Ur is mapped to VR, Sigma R, and then Ur + 1 is mapped to zero and we are assuming that m is greater than equal to n, for now Ur r + 1 through u, m is mapped to zero. the beautiful thing that the SVD does okay is it provides a very special provides- sorry, R is a little funky. it provides an orthogonal basis for the four fundamental subspaces of a. and what are the four fundamental subspaces? and some of you might have seen this in your, in your linear algebra class, it's the column space of the Matrix, a, which is often denoted as range space of a. the other is the row space of the Matrix and you probably saw right that the row rank in in your, in your undergraduate linear algebra course, that the row rank is the same as the column rank, right, and it just falls out of the SVD, right? it's the. I can write the range space of a transpose. then I have the null space, which is m space of a. I have n space of a of a transpose is equal to m space of aace. I don't need to get all fancy over here.but also, you know, you can truncate the SVD at any K. you can, you know, if the full SVD is U, Sigma, V, transpose, as given over here, right, the thin, the. the thin SVD is sometimes called this U hat, which takes where m is greater than equal to n, and you take the first n singular vectors, U hat, Sigma hat, V, had, transpose. but you can truncate it at any K. you can just take U1, U2, for example, or U1, U2, u3, and then take the corresponding singular values- they are of course ordered in decreasing order- and then also the corresponding v's, and that is sometimes called the K truncated SVD. and one of the really nice properties of the SVD is that that gives the best rank K approximation to the given Matrix, right? for example, here you know, if you have a given Matrix a and you want to find out the best ranky approximation of this Matrix, then you can basically just take, you know, U, K, Sigma K, VK transpose. where UK is n by M by K, maybe I should write it over here: Sigma U, UK belongs to our M by K, Sigma K belongs to r, k by K and VK belongs to R NYK, okay, and that gives you the, the, the S, the best singular value, best truncated, best rank ranky approximation. okay, then we went back to Le squares regression and we saw that LE squares regression, if you analyze it using the SVD, it's just the orthogonal projector onto the rain space of the design Matrix, which is X transpose, right, which is made of the training samples. today we will kind of talk a little bit more about regression, some of the issues that there are with just doing regression as we've talked about it, for example e squares regression- and talk about something that is really needed to make the regression better, which is regularization in regression, and there we'll look at a particular way to regularize which makes the prediction better, and we will see that we can analyze this method, called Ridge regression, quite well by looking at the singular value, decomposition. okay, reminder that regression is, you know, I have training data and XI, Yi, XI is D dimensional D features the Y's. since we are talking about regression, these are real numbers and linear regression is basically taking a linear combination which is W + W1, X1 + W2, X2 plus WB, XD.okay, and it is. it is true for all, okay, okay, which means that, and remember that AK is equal to UK K, Sigma K we okay with. with that I kind of conclude talking about the singular value de composition. but it's really a, an amazing decomposition among all Matrix decompositions that exist. any questions far? I'm now going to move on to regression and see how the SVD can be. you know how the SVD helps us over there. I have a question: if I made those Sigma values, the singular values, Sigma 1 to Sigma n, okay, when we do the, the K rank, you mentioned that these are kind of sorted: the sigma is, the is the greatest one and the biggest, and then all the way to Sigma n. when we the the K rank thing are the, let's say we do k equals 2, Sigma 1 and sigma 2 are the, the exact value of the, the full de composite, exactly they are exactly this Sigma one and this Sigma 2. basically it's saying that I can take this decomposition, which is the full SVD, and I can basically just take any K left singular vectors, any K, the top K singular values and the top K right singular vector. and If I multiply them out, UK Sigma K, VK transpose, then among all possible ranky approximations of a, this is the closest to a. that's pretty powerful. yes, it's.I have a question: if I made those Sigma values, the singular values, Sigma 1 to Sigma n, okay, when we do the, the K rank, you mentioned that these are kind of sorted: the sigma is, the is the greatest one and the biggest, and then all the way to Sigma n. when we the the K rank thing are the, let's say we do k equals 2, Sigma 1 and sigma 2 are the, the exact value of the, the full de composite, exactly they are exactly this Sigma one and this Sigma 2. basically it's saying that I can take this decomposition, which is the full SVD, and I can basically just take any K left singular vectors, any K, the top K singular values and the top K right singular vector. and If I multiply them out, UK Sigma K, VK transpose, then among all possible ranky approximations of a, this is the closest to a. that's pretty powerful. yes, it's. it's a beautiful property and somewhat surprising, if you know, if you, if you think about it, really it's kind of a. if I just look at this particular particular problem over here and I think about trying to solve it, this particular problem, it's not clear that there is a closed rank solution. this problem is not really even convex, because rank is not a kind of convex function, but it's just kind of the wonders of single value decomposition, that have this nested property. it's basically a nested property. yeah, yeah, it's just, you can some sort of partition, The Matrix you want, and then that, yeah, that's yeah beautiful, yeah, yeah, yeah. I mean I can't stop gushing about the SVD, but it's really kind of a remarkable decomposition. it helps us in. I said, it helps us in interpretation of many things.

                **Question**: Why does the SVD of a matrix reveal its rank?

In [8]:
# Step 3.4: Generate an answer using OpenAI LLM
the_llm_agent = create_agent(role_name="RAG Agent", description="", key=OpenAI_API_KEY, model=LLM_Model, temperature=0.0)
the_llm_agent.sendMessage(prompt)
answer = the_llm_agent.getResponse()
print("\nBig LLM Answer:\n")
print(answer)
#display(Latex(answer))

Big LLM Answer:

The SVD of a matrix reveals its rank because the number of nonzero singular values in the SVD is exactly equal to the rank of the matrix. The singular values in the SVD are ordered from greatest to smallest, and by examining these singular values, one can determine the rank of the matrix effectively.

# Evaluation Functions

In [9]:
# Step 4: Define the evaluation function

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.tokenize import word_tokenize
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
import bert_score

# LLM evaluator
def evaluate_with_llm(reference_answer, generated_answer, model="gpt-4o", temperature=0.0):
    """
    Evaluates the quality of a generated answer against the reference answer using your custom LLM agent.
    """
    # Build the prompt
    prompt = f"""You are an expert evaluator.
You are given a reference answer and a generated answer.
Evaluate the generated answer based on how well it aligns with the reference answer.

Reference Answer:
{reference_answer}

Generated Answer:
{generated_answer}

Score the generated answer from 0 to 10:
- 0: Completely wrong, irrelevant, or nonsensical
- 5: Somewhat correct but incomplete, inaccurate, or partially aligned
- 10: Fully correct, well-aligned, and comprehensive

Only return the score as an integer number between 0 and 10. Nothing else."""
    
    try:
        # Create the evaluator agent
        evaluator_agent = create_agent(
            role_name="Evaluator Agent",
            description="An expert in evaluating alignment between answers.",
            key=OpenAI_API_KEY,
            model=model,
            temperature=temperature
        )
        
        # Send the prompt and get the response
        evaluator_agent.sendMessage(prompt)
        answer = evaluator_agent.getResponse()
        
        # Parse the score
        score_text = answer.strip()
        score = int(score_text)
        score = max(0, min(10, score))  # Clamp between 0 and 10
        
    except Exception as e:
        print(f"LLM evaluation error: {e}")
        score = 0
    
    return score

def evaluate(prediction, reference):
    """
    Evaluate a single prediction against a single reference using BLEU, ROUGE-L, BERTScore, and LLM_eval.
    Args:
        prediction (str): The generated answer.
        reference (str): The ground truth answer.
    Returns:
        dict: Dictionary with BLEU, ROUGE-L F1, BERTScore F1, and LLM evaluation score.
    """

    # Tokenize both
    pred_tokens = word_tokenize(prediction)
    ref_tokens = word_tokenize(reference)

    # BLEU (single sentence with smoothing)
    smoothing = SmoothingFunction().method1
    bleu = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smoothing)

    # ROUGE-L (single sentence)
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    rougeL = scorer.score(reference, prediction)
    avg_rougeL = rougeL['rougeL'].fmeasure

    # BERTScore (single sentence) -- must wrap in list
    P, R, F1 = bert_score.score([prediction], [reference], lang="en", rescale_with_baseline=True)
    avg_bertF1 = float(F1.mean())

    # LLM Evaluation
    llm_score = evaluate_with_llm(reference, prediction)
    # print(f"Inside evaluation:\nReference: {reference}\nGenerated: {prediction}\nllm_score: {llm_score}\n")

    return {
        'bleu': bleu,
        'avg_rougeL': avg_rougeL,
        'avg_bertF1': max(0.0, avg_bertF1),
        'LLM_eval': llm_score
    }

# Evaluation Loop

In [10]:
import pandas as pd
import logging
from IPython.display import display, HTML, Markdown

logging.getLogger("transformers.modeling_utils").setLevel(logging.ERROR)

# Read the CSV file
df = pd.read_csv("sample_questions/ML_questions.csv", encoding="utf-8")
   
# Normalize the column names
df.columns = (
    df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", "_", regex=True)
        .str.replace(r"[^\w_]", "", regex=True)
)

df_avgs = {}

for k in range(2,11):
    results = []
    # Loop through each model
    for model_name in openai_models:
        
        # RAG Loop
        for _, row in tqdm(df.iterrows(), 
                            total=len(df), 
                            desc=f"Evaluating {model_name}",):
            question  = row["question"]
            reference = row["answer"]
            
            chunks = retrieve(question, all_chunks, index, k=k)
            prompt = build_prompt(question, chunks)
            agent = create_agent(
                role_name="RAG Agent",
                description="You are a helpful TA.",
                key=OpenAI_API_KEY,
                model=model_name,
                temperature=0.0,
            )
            agent.sendMessage(prompt)
            prediction = agent.getResponse()
    
            # print(f"Question: {question}\nReference: {reference}\nPrediction: {prediction}\n")
            scores = evaluate(prediction, reference)
            scores["model"] = model_name
            results.append(scores)
    
    # Convert results to DataFrame and calculate average scores
    df_scores = pd.DataFrame(results)
    df_avg = (df_scores.groupby("model", as_index=False).mean())
    df_avgs[k] = df_avg
    
    # Now generate LaTeX table
    latex_table = "\\begin{table}[h]\n"
    latex_table += "\\centering\n"
    latex_table += "\\caption{Main results for k="+str(k)+". Higher is better.}\n"
    latex_table += "\\label{tab:main}\n"
    
    # Define the columns manually or from df_avg
    columns = df_avg.columns.tolist()
    
    # LaTeX header
    header = " & ".join(["\\textbf{" + col.replace("_", " ").title() + "}" for col in columns])
    latex_table += "\\begin{tabular}{" + "l" + "c" * (len(columns) - 1) + "}\n"
    latex_table += "\\toprule\n"
    latex_table += header + " \\\\\n"
    latex_table += "\\midrule\n"
    
    # Rows
    for _, row in df_avg.iterrows():
        row_data = " & ".join(
            f"{val:.1f}" if isinstance(val, (float, int)) else str(val) 
            for val in row
        )
        latex_table += row_data + " \\\\\n"
    
    latex_table += "\\bottomrule\n"
    latex_table += "\\end{tabular}\n"
    latex_table += "\\end{table}"
    
    # 1. Show an HTML preview of your averaged results
    html = df_avg.to_html(index=False,
                          float_format=lambda x: f"{x:.1f}")
    display(HTML(html))
    
    # 2. Then show the full LaTeX for copy-paste
    latex_block = f"""```latex
    {latex_table}
    ```"""
    display(Markdown(latex_block))

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [02:00<00:00,  2.40s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:04<00:00,  2.50s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [02:46<00:00,  3.32s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:15<00:00,  3.91s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:22<00:00,  2.85s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:05<00:00,  2.51s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=2. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.0 & 0.2 & 0.3 & 7.6 \\
gpt-3.5-turbo-16k & 0.0 & 0.2 & 0.2 & 7.3 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 6.2 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 7.6 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 7.4 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 7.5 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [01:57<00:00,  2.36s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:10<00:00,  2.62s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [02:50<00:00,  3.41s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:32<00:00,  4.25s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:19<00:00,  2.79s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:16<00:00,  2.73s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=3. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.0 & 0.2 & 0.3 & 8.0 \\
gpt-3.5-turbo-16k & 0.1 & 0.2 & 0.2 & 7.4 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.2 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 7.8 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 7.7 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 7.6 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [01:55<00:00,  2.32s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:01<00:00,  2.44s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [02:56<00:00,  3.54s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:31<00:00,  4.23s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:31<00:00,  3.03s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:12<00:00,  2.65s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=4. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.1 & 0.2 & 0.3 & 8.1 \\
gpt-3.5-turbo-16k & 0.0 & 0.2 & 0.3 & 7.8 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.1 \\
gpt-4-turbo & 0.1 & 0.2 & 0.2 & 7.8 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 7.8 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 7.6 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [02:06<00:00,  2.53s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:21<00:00,  2.83s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [03:18<00:00,  3.98s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:56<00:00,  4.73s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:21<00:00,  2.83s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:31<00:00,  3.02s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=5. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.1 & 0.3 & 0.3 & 8.5 \\
gpt-3.5-turbo-16k & 0.1 & 0.2 & 0.3 & 8.5 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.4 \\
gpt-4-turbo & 0.1 & 0.2 & 0.2 & 8.4 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 8.2 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 7.9 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [01:48<00:00,  2.16s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:16<00:00,  2.72s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [03:05<00:00,  3.72s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [04:02<00:00,  4.85s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:25<00:00,  2.92s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:17<00:00,  2.74s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=6. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.1 & 0.3 & 0.3 & 8.3 \\
gpt-3.5-turbo-16k & 0.0 & 0.2 & 0.3 & 8.1 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.3 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 8.1 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 8.2 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 8.0 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [02:04<00:00,  2.50s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:04<00:00,  2.50s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [03:20<00:00,  4.01s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:48<00:00,  4.56s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:27<00:00,  2.96s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:17<00:00,  2.75s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=7. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.0 & 0.2 & 0.3 & 8.4 \\
gpt-3.5-turbo-16k & 0.1 & 0.3 & 0.3 & 8.7 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.6 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 8.4 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 8.3 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 8.1 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [01:55<00:00,  2.32s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:15<00:00,  2.70s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [03:12<00:00,  3.86s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:54<00:00,  4.68s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:24<00:00,  2.88s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:19<00:00,  2.79s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=8. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.1 & 0.2 & 0.3 & 8.8 \\
gpt-3.5-turbo-16k & 0.1 & 0.3 & 0.3 & 8.5 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.5 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 8.2 \\
gpt-4o & 0.1 & 0.2 & 0.2 & 8.5 \\
gpt-4o-mini & 0.0 & 0.2 & 0.2 & 8.3 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [02:43<00:00,  3.28s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:10<00:00,  2.60s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [03:08<00:00,  3.77s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [04:19<00:00,  5.20s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [02:26<00:00,  2.93s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:15<00:00,  2.71s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=9. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.1 & 0.3 & 0.3 & 8.3 \\
gpt-3.5-turbo-16k & 0.1 & 0.3 & 0.3 & 8.4 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 7.8 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 8.3 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 8.3 \\
gpt-4o-mini & 0.1 & 0.2 & 0.2 & 8.3 \\
\bottomrule
\end{tabular}
\end{table}
    ```

Evaluating gpt-3.5-turbo: 100%|███████████████████████████████| 50/50 [01:54<00:00,  2.28s/it]
Evaluating gpt-3.5-turbo-16k: 100%|███████████████████████████| 50/50 [02:22<00:00,  2.85s/it]
Evaluating gpt-4-turbo: 100%|█████████████████████████████████| 50/50 [03:32<00:00,  4.25s/it]
Evaluating gpt-4: 100%|███████████████████████████████████████| 50/50 [03:59<00:00,  4.79s/it]
Evaluating gpt-4o-mini: 100%|█████████████████████████████████| 50/50 [04:19<00:00,  5.19s/it]
Evaluating gpt-4o: 100%|██████████████████████████████████████| 50/50 [02:22<00:00,  2.85s/it]

```latex
    \begin{table}[h]
\centering
\caption{Main results for k=10. Higher is better.}
\label{tab:main}
\begin{tabular}{lcccc}
\toprule
\textbf{Model} & \textbf{Bleu} & \textbf{Avg Rougel} & \textbf{Avg Bertf1} & \textbf{Llm Eval} \\
\midrule
gpt-3.5-turbo & 0.1 & 0.3 & 0.3 & 8.7 \\
gpt-3.5-turbo-16k & 0.1 & 0.2 & 0.3 & 8.1 \\
gpt-4 & 0.0 & 0.2 & 0.2 & 8.0 \\
gpt-4-turbo & 0.0 & 0.2 & 0.2 & 8.7 \\
gpt-4o & 0.0 & 0.2 & 0.2 & 8.3 \\
gpt-4o-mini & 0.1 & 0.2 & 0.2 & 8.4 \\
\bottomrule
\end{tabular}
\end{table}
    ```

# Show Evaluation Metrics

# Scratchpad

In [ ]:
# import os
# import re

# def clean_transcript(file_path):
#     # Derive the output filename by removing the trailing 'c' before .txt
#     base_name = os.path.basename(file_path)
#     if not base_name.endswith('c.txt'):
#         print(f"Skipped non-matching file: {file_path}")
#         return
    
#     output_name = base_name[:-5] + '.txt'  # remove 'c' and add '.txt'
#     output_path = os.path.join(os.path.dirname(file_path), output_name)

#     with open(file_path, 'r', encoding='utf-8') as infile:
#         lines = infile.readlines()

#     cleaned_lines = []
#     i = 0
#     while i < len(lines) - 2:
#         name1 = lines[i].strip()
#         name2 = lines[i + 1].strip()
#         time = lines[i + 2].strip()

#         if name1 == name2 and re.match(r'^\d{2}:\d{2}:\d{2}$', time):
#             i += 3  # skip these three lines
#         else:
#             cleaned_lines.append(lines[i])
#             i += 1

#     # Add any remaining lines at the end
#     while i < len(lines):
#         cleaned_lines.append(lines[i])
#         i += 1

#     with open(output_path, 'w', encoding='utf-8') as outfile:
#         outfile.writelines(cleaned_lines)

#     print(f"Cleaned file saved as: {output_path}")


# # Example usage
# clean_transcript("lecture-13c.txt")

In [ ]:
# from IPython.display import display, Latex

# # Display equation
# display(Math(r'E = mc^2'))

# # For text + equation
# display(Latex(r'The quadratic formula is: $x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$'))